name: Test and Deploy to Netlify

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout main 
        uses: actions/checkout@v4

      - name: set up node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18.x

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build
        env:
          SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}

  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout main 
        uses: actions/checkout@v4

      - name: set up node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18.x

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build
        env:
          SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
        
      - name: run tests
        env:
          CI: true
        run: npm test  

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout main 
        uses: actions/checkout@v4

      - name: set up node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18.x

      - name: install dependencies
        run: npm ci

      - name: build react.js
        run: npm run build

      - name: deploy
        uses: nwtgck/actions-netlify@v1.1.4
        with:
          publish-dir: './build'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}